# -*- coding: utf-8 -*-
"""fldqn_main_review_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12yFyECVlhB48cadmA2UAgQ1wlR6ZfyTL

**📦 SNIPPET 1: Imports and **Setup****
"""

# ============================================================
# SNIPPET 1: ALL IMPORTS
# Install if needed: pip install tensorflow scikit-learn simpy
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.layers import Dense, LSTM, Input

from collections import deque
import random
import warnings
import os

warnings.filterwarnings('ignore')

# Fix random seeds so results are reproducible
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)
random.seed(SEED)

print("All imports done!")
print(f"TensorFlow version: {tf.__version__}")

"""**📂 SNIPPET 2: Load Your GoCJ Dataset**"""

# ============================================================
# SNIPPET 2: LOAD YOUR GoCJ DATASET
#
# Your files contain one MI value per line like:
#   83000
#   95000
#   91000
#   ...
#
# MI = Million Instructions = how heavy the task is
# Think of it as: weight of a package a delivery person must carry
# ============================================================

def load_gocj_dataset(filepath):
    """
    Load GoCJ dataset.
    Each line = size of one job in Million Instructions (MI).

    Args:
        filepath: path to your .txt file
    Returns:
        numpy array of MI values
    """
    values = []
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if line:  # skip empty lines
                values.append(float(line))
    return np.array(values)

# ============================================================
# FILE PATHS HERE:
# ============================================================
small_mi  = load_gocj_dataset('/content/sample_data/GoCJ Datasets/GoCJ_Dataset_100.txt')   # 100 tasks
medium_mi = load_gocj_dataset('/content/sample_data/GoCJ Datasets/GoCJ_Dataset_500.txt')   # 500 tasks
large_mi  = load_gocj_dataset('/content/sample_data/GoCJ Datasets/GoCJ_Dataset_1000 (2).txt')  # 1000 tasks

print(f"Small  dataset: {len(small_mi)} tasks | Min MI: {small_mi.min():.0f} | Max MI: {small_mi.max():.0f}")
print(f"Medium dataset: {len(medium_mi)} tasks | Min MI: {medium_mi.min():.0f} | Max MI: {medium_mi.max():.0f}")
print(f"Large  dataset: {len(large_mi)} tasks | Min MI: {large_mi.min():.0f} | Max MI: {large_mi.max():.0f}")
print(f"\nSample values (first 5): {small_mi[:5]}")

"""**⚙️ SNIPPET 3: Convert MI Values to Task Features**"""

# ============================================================
# SNIPPET 3: GENERATE TASK PARAMETERS FROM MI VALUES
#
# Real-life analogy:
# MI value = how heavy the surgery/package is
# Execution time = how long it takes (heavier = longer)
# Deadline = when it MUST be done (some urgent, some flexible)
# CPU requirement = how many doctors/desks are needed
# ============================================================

def generate_tasks_from_mi(mi_values, processing_speed=1000, random_seed=42):
    """
    Convert raw MI values to full task feature set.

    Paper uses:
    Ti = [execution_time (xi), deadline (yi)]  ← equation (1)

    Args:
        mi_values       : raw job sizes in MI
        processing_speed: VM speed in MIPS (Million Instructions Per Second)

    Returns:
        DataFrame with columns: task_id, mi_value, exec_time, deadline, cpu_req, priority
    """
    np.random.seed(random_seed)
    n = len(mi_values)

    # Step 1: Raw execution time = MI / processing_speed (seconds)
    raw_exec = mi_values / processing_speed

    # Step 2: Normalize to [1, 100] range for simulation
    # Formula: x_norm = (x - min) / (max - min) * 99 + 1
    exec_min, exec_max = raw_exec.min(), raw_exec.max()
    exec_times = (raw_exec - exec_min) / (exec_max - exec_min + 1e-8) * 99 + 1

    # Step 3: Deadline = exec_time × random factor [1.2, 2.5]
    # 1.2 = very urgent (tight deadline)
    # 2.5 = flexible (plenty of time)
    deadline_factors = np.random.uniform(1.2, 2.5, n)
    deadlines = exec_times * deadline_factors

    # Step 4: CPU requirement proportional to MI, scaled to [0.1, 1.0]
    cpu_min, cpu_max = mi_values.min(), mi_values.max()
    cpu_req = (mi_values - cpu_min) / (cpu_max - cpu_min + 1e-8) * 0.9 + 0.1

    tasks_df = pd.DataFrame({
        'task_id'  : np.arange(n),
        'mi_value' : mi_values,
        'exec_time': exec_times,   # xi in paper
        'deadline' : deadlines,    # yi in paper
        'cpu_req'  : cpu_req,
        'priority' : 0             # Will be set by K-Means
    })

    return tasks_df

# Generate tasks for all three dataset sizes
tasks_small  = generate_tasks_from_mi(small_mi)
tasks_medium = generate_tasks_from_mi(medium_mi)
tasks_large  = generate_tasks_from_mi(large_mi)

print("Sample task data (small dataset):")
print(tasks_small.head(5).to_string(index=False))
print(f"\nExecution time range: {tasks_small['exec_time'].min():.2f} - {tasks_small['exec_time'].max():.2f}")
print(f"Deadline range:       {tasks_small['deadline'].min():.2f} - {tasks_small['deadline'].max():.2f}")

"""**🎯 SNIPPET 4: K-Means Clustering for Task Priority**"""

# ============================================================
# SNIPPET 4: K-MEANS TASK PRIORITIZATION
#
# Paper Section III.A — Algorithm 1
#
# Real-life example (Hospital Triage):
# Triage nurse looks at TWO things:
#   1. How long will treatment take? (exec_time)
#   2. When does patient NEED it by? (deadline)
#
# Patient needing 3-hour surgery with 4-hour deadline → HIGH PRIORITY
# Patient needing 10-min bandage with 2-day deadline  → LOW PRIORITY
#
# K-Means groups similar patients together automatically.
# ============================================================

def kmeans_task_prioritization(tasks_df, k=3):
    """
    Cluster tasks into k priority groups using K-Means.

    Features: [exec_time, deadline]  ← from paper equation (1)
    Objective: Minimize J = Σ Σ ||Ti - μk||²  ← equation (2)
    Centroid:  μk = (1/|Ck|) Σ Ti             ← equation (3)

    Priority assignment (equations 6-9):
    - HIGH   : high exec_time AND low deadline
    - LOW    : low exec_time AND high deadline
    - MEDIUM : everything else

    Returns:
        tasks_df with priority column filled
        kmeans model, scaler, cluster statistics
    """
    df = tasks_df.copy()

    # Step 1: Extract 2D feature space [exec_time, deadline]
    X = df[['exec_time', 'deadline']].values

    # Step 2: Standardize features (both should have equal importance)
    # Without this, 'deadline' values might dominate just because they're larger
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Step 3: K-Means clustering (Algorithm 1 from paper)
    kmeans = KMeans(
        n_clusters=k,       # K=3 as per paper
        n_init=10,          # Run 10 times, pick best result
        max_iter=300,       # Max iterations for convergence
        random_state=42
    )
    df['cluster'] = kmeans.fit_predict(X_scaled)

    # Step 4: Compute average exec_time (ek) and deadline (dk) per cluster
    # Equations (4) and (5) from paper
    cluster_stats = df.groupby('cluster').agg(
        avg_exec=('exec_time', 'mean'),   # ek = mean execution time
        avg_deadline=('deadline', 'mean') # dk = mean deadline
    )

    # Step 5: Assign priority based on urgency score
    # Urgency = exec_time / deadline
    # HIGH urgency = large exec_time + small deadline (can't afford to wait)
    cluster_stats['urgency'] = cluster_stats['avg_exec'] / cluster_stats['avg_deadline']
    ranked = cluster_stats['urgency'].rank(ascending=False)

    # Map cluster index → priority label (equations 6, 7, 8, 9)
    priority_label_map = {}
    priority_num_map   = {}
    for cluster_id, rank_val in ranked.items():
        if rank_val == 1:
            priority_label_map[cluster_id] = 'high'
            priority_num_map[cluster_id]   = 2   # s3 = 2 for high (eq. 24)
        elif rank_val == 2:
            priority_label_map[cluster_id] = 'medium'
            priority_num_map[cluster_id]   = 1   # s3 = 1 for medium
        else:
            priority_label_map[cluster_id] = 'low'
            priority_num_map[cluster_id]   = 0   # s3 = 0 for low

    df['priority_label'] = df['cluster'].map(priority_label_map)
    df['priority']       = df['cluster'].map(priority_num_map)

    cluster_stats['priority'] = cluster_stats.index.map(priority_label_map)

    return df, kmeans, scaler, cluster_stats


# Apply K-Means to all datasets
print("Applying K-Means clustering...")
tasks_small,  km_small,  sc_small,  stats_small  = kmeans_task_prioritization(tasks_small)
tasks_medium, km_medium, sc_medium, stats_medium = kmeans_task_prioritization(tasks_medium)
tasks_large,  km_large,  sc_large,  stats_large  = kmeans_task_prioritization(tasks_large)

print("\nSmall dataset priority distribution:")
print(tasks_small['priority_label'].value_counts().to_string())
print("\nCluster statistics (small):")
print(stats_small[['avg_exec','avg_deadline','urgency','priority']].to_string())

"""**📊 SNIPPET 5: Visualize K-Means Clusters**"""

# ============================================================
# SNIPPET 5: VISUALIZE K-MEANS CLUSTERS
# Reproduces Figures 4, 5, 6 from the paper
# ============================================================

def plot_kmeans_clusters(tasks_df, title="Task Priority Clusters (K-Means)"):
    """
    Scatter plot: X=Execution Time, Y=Deadline
    Colors: Red=High, Orange=Medium, Green=Low priority

    Real-life: Each dot = one patient
    Position tells urgency at a glance
    """
    color_map = {'high': 'red', 'medium': 'orange', 'low': 'green'}
    label_map = {'high': 'High Priority', 'medium': 'Medium Priority', 'low': 'Low Priority'}
    marker_map = {'high': '^', 'medium': 's', 'low': 'o'}

    plt.figure(figsize=(8, 6))

    for priority in ['high', 'medium', 'low']:
        mask = tasks_df['priority_label'] == priority
        subset = tasks_df[mask]
        plt.scatter(
            subset['exec_time'],
            subset['deadline'],
            c=color_map[priority],
            label=label_map[priority],
            marker=marker_map[priority],
            alpha=0.7,
            edgecolors='black',
            linewidth=0.4,
            s=60
        )

    plt.xlabel('Execution Time (units)', fontsize=12)
    plt.ylabel('Deadline (units)', fontsize=12)
    plt.title(title, fontsize=13, fontweight='bold')
    plt.legend(fontsize=10)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

    print(f"Priority counts: {tasks_df['priority_label'].value_counts().to_dict()}")

# Plot for all three datasets
plot_kmeans_clusters(tasks_small,  f"Task Priority (K-Means) — Small Dataset  ({len(tasks_small)} tasks)")
plot_kmeans_clusters(tasks_medium, f"Task Priority (K-Means) — Medium Dataset ({len(tasks_medium)} tasks)")
plot_kmeans_clusters(tasks_large,  f"Task Priority (K-Means) — Large Dataset  ({len(tasks_large)} tasks)")

"""**🏥 SNIPPET 6: Fog Computing Environment**"""

# ============================================================
# SNIPPET 6: FOG COMPUTING ENVIRONMENT (Simulation)
#
# Simulation Parameters from Paper Table 2:
#   - 10 Fog Nodes (10 hospitals)
#   - 6 VMs per Node (6 operation theaters each)
#   - 60 VMs total
#
# Real-life: This class simulates the hospital network.
# When a task is "assigned to VM #3", this class checks:
#   - Is VM #3 free enough?
#   - Will the task finish before its deadline?
#   - How much energy is used?
# ============================================================

class FogEnvironment:
    """
    Simulates the fog computing environment.
    Handles task assignment, resource tracking, and metric computation.
    """

    # Paper's simulation parameters (Table 2)
    NUM_NODES       = 10    # Fog nodes
    NUM_VMS_PER_NODE = 6   # VMs per node
    BANDWIDTH       = 200   # MBPS

    def __init__(self, num_nodes=10, num_vms_per_node=6, seed=42):
        np.random.seed(seed)
        self.num_nodes        = num_nodes
        self.num_vms_per_node = num_vms_per_node
        self.total_vms        = num_nodes * num_vms_per_node

        # Each VM has a total processing capacity (available time budget)
        # Heterogeneous: different VMs have different speeds (realistic)
        self.vm_capacities = np.random.uniform(50, 300, self.total_vms)

        # Power consumption rate per VM (Pj in paper equation 14)
        # Think: some operation theaters consume more electricity
        self.vm_power = np.random.uniform(0.5, 2.0, self.total_vms)

        # Tracking variables (reset each episode)
        self.vm_queue_lengths  = None   # s1: how many tasks waiting at each VM
        self.vm_available_time = None   # remaining capacity
        self.vm_assigned_tasks = None   # tasks assigned to each VM

        self.reset()

    def reset(self):
        """Reset all VMs for a fresh episode."""
        self.vm_queue_lengths  = np.zeros(self.total_vms)
        self.vm_available_time = self.vm_capacities.copy()
        self.vm_assigned_tasks = [[] for _ in range(self.total_vms)]

    def get_state(self, task):
        """
        Build state vector s = [s1, s2, s3] from paper equations 22-25.

        s1 = VM queue state (we summarize with stats)
        s2 = CPU requirement of task      ← equation (23)
        s3 = priority of task (0/1/2)     ← equation (24)

        Full state vector (equation 25): s = [s1, s2, s3]
        """
        state = np.array([
            self.vm_queue_lengths.mean(),   # average load across all VMs
            self.vm_queue_lengths.max(),    # most loaded VM
            self.vm_queue_lengths.min(),    # least loaded VM
            np.std(self.vm_queue_lengths),  # load imbalance
            float(task['cpu_req']),         # s2: CPU demand of this task
            float(task['priority']),        # s3: task urgency (0/1/2)
            float(task['exec_time']),       # how long this task takes
            float(task['deadline']),        # when it must be done by
        ], dtype=np.float32)
        return state

    def step(self, task, vm_idx):
        """
        Assign task to VM[vm_idx].

        Checks:
        1. Does VM have enough capacity? (equation 10: Available_Time(Fj) >= Exec_Time(Ti))
        2. Will it complete before deadline?
        3. Compute reward (equation 28)

        Returns:
            next_state, reward, sla_violated (bool), rejected (bool)
        """
        exec_time = float(task['exec_time'])
        deadline  = float(task['deadline'])

        # Check equation (10): Available Time(Fj) >= Exec Time(Ti)
        if self.vm_available_time[vm_idx] >= exec_time:
            # ACCEPT the task
            self.vm_available_time[vm_idx] -= exec_time
            self.vm_queue_lengths[vm_idx]  += 1
            self.vm_assigned_tasks[vm_idx].append(task)

            # Estimate completion time:
            # Base exec_time + small queuing delay (tasks waiting ahead)
            queue_delay      = self.vm_queue_lengths[vm_idx] * 0.5
            completion_time  = exec_time + queue_delay

            # Check SLA (equation 13): did task finish before deadline?
            if completion_time <= deadline:
                reward       = 10    # +10 for on-time completion (eq. 28)
                sla_violated = False
                rejected     = False
            else:
                reward       = -5    # -5 for deadline missed (eq. 28)
                sla_violated = True
                rejected     = False
        else:
            # REJECT — VM overloaded
            reward       = -10   # -10 for rejection (eq. 28)
            sla_violated = False
            rejected     = True

        # Get next state (after this assignment)
        next_state = self.get_state(task)

        return next_state, reward, sla_violated, rejected

    def compute_makespan(self):
        """
        Makespan = max completion time across all VMs (equation 11).
        Real-life: Total time from when work started to when ALL tasks are done.
        """
        # Makespan = max queue length (proxy for total processing time)
        used_capacities = self.vm_capacities - self.vm_available_time
        return float(np.max(used_capacities)) if np.any(used_capacities > 0) else 1.0

    def compute_throughput(self, makespan):
        """
        Throughput = tasks completed / makespan (equation 12).
        Real-life: How many surgeries per hour?
        """
        total_completed = sum(len(vt) for vt in self.vm_assigned_tasks)
        return total_completed / makespan if makespan > 0 else 0

    def compute_energy(self):
        """
        Total energy = Σ (Pj × Σ exec_time_of_tasks_at_Fj)  equation (14, 15)
        Real-life: Total electricity bill for all theaters combined.
        """
        total_energy = 0.0
        for vm_idx in range(self.total_vms):
            tasks_at_vm = self.vm_assigned_tasks[vm_idx]
            if tasks_at_vm:
                total_exec = sum(float(t['exec_time']) for t in tasks_at_vm)
                total_energy += self.vm_power[vm_idx] * total_exec
        return total_energy

    def get_all_metrics(self):
        """Compute all paper metrics in one call."""
        makespan   = self.compute_makespan()
        throughput = self.compute_throughput(makespan)
        energy     = self.compute_energy()
        return {'makespan': makespan, 'throughput': throughput, 'energy': energy}

"""**🧠 SNIPPET 7: DQN Neural Network**"""

# ============================================================
# SNIPPET 7: DQN MODEL (Neural Network)
#
# Architecture from paper Section IV.F:
# Input → 128 neurons (ReLU) → 64 neurons (ReLU) → Output (Q-values)
#
# Real-life analogy:
# This is the manager's BRAIN.
# Input  = current situation (how busy are VMs, what's the task?)
# Output = score for each VM ("How good is it to assign to VM #0?")
#          The manager picks the VM with the HIGHEST score.
# ============================================================

STATE_SIZE  = 8    # [avg_q, max_q, min_q, std_q, cpu_req, priority, exec_time, deadline]
ACTION_SIZE = 6    # = num_vms_per_node (agent selects within its own node)

def build_dqn_model(state_size=STATE_SIZE, action_size=ACTION_SIZE):
    """
    Build the Deep Q-Network.

    Input  → state representation (what does the manager see?)
    Output → Q-value for each VM (how good is each option?)

    Architecture (paper Section IV.F):
    Layer 1: 128 neurons + ReLU  ← learn basic patterns
    Layer 2: 64  neurons + ReLU  ← learn complex relationships
    Output : action_size neurons ← one Q-value per VM
    """
    model = models.Sequential([
        Dense(128, activation='relu', input_shape=(state_size,), name='hidden_1'),
        Dense(64,  activation='relu',                            name='hidden_2'),
        Dense(action_size, activation='linear',                  name='q_output')
        # Linear output: Q-values can be any number (positive or negative)
    ])

    model.compile(
        optimizer=optimizers.Adam(learning_rate=0.001),  # α = 0.001 (paper)
        loss='mse'   # Mean Squared Error: minimize (predicted_Q - target_Q)²
    )
    return model

# Test model
test_model = build_dqn_model()
test_model.summary()

"""**📝 SNIPPET 8: Experience Replay Buffer**"""

# ============================================================
# SNIPPET 8: EXPERIENCE REPLAY BUFFER
#
# Real-life analogy:
# The manager keeps a NOTEBOOK of past decisions:
# "Situation: VM3 was free, task was urgent, CPU=0.8
#  I chose: VM3
#  Result: +10 (task done on time!)"
#
# During training, manager RANDOMLY reviews old notebook entries.
# This prevents over-learning from just recent events.
# (Like not just studying the last chapter before exam — study ALL chapters)
# ============================================================

class ReplayBuffer:
    """
    Fixed-size memory buffer storing (state, action, reward, next_state) tuples.

    Paper says: "experience replay stores previous scheduling decisions
    along with their outcomes in a replay buffer" — Section IV.A
    """

    def __init__(self, capacity=2000):
        # deque automatically drops oldest entries when full
        self.buffer   = deque(maxlen=capacity)
        self.capacity = capacity

    def push(self, state, action, reward, next_state):
        """Store one experience tuple."""
        self.buffer.append((state, action, reward, next_state))

    def sample(self, batch_size=32):
        """
        Randomly sample batch_size experiences.
        Random sampling breaks correlation between consecutive steps.
        """
        batch = random.sample(self.buffer, min(batch_size, len(self.buffer)))
        states, actions, rewards, next_states = zip(*batch)
        return (
            np.array(states,      dtype=np.float32),
            np.array(actions,     dtype=np.int32),
            np.array(rewards,     dtype=np.float32),
            np.array(next_states, dtype=np.float32)
        )

    def __len__(self):
        return len(self.buffer)

    def is_ready(self, batch_size=32):
        """Check if enough samples exist to train."""
        return len(self.buffer) >= batch_size

"""**🤖 SNIPPET 9: DQN Agent (Local Manager at Each Fog Node)**"""

# ============================================================
# SNIPPET 9: DQN AGENT
#
# One DQNAgent lives at each fog node.
# It makes LOCAL task assignment decisions.
# Later, agents share weights via federated learning.
#
# Hyperparameters (paper Section IV.F):
#   α (learning rate)  = 0.001
#   γ (discount)       = 0.95  ← future rewards matter 95%
#   ε (exploration)    = 1.0   ← start fully random, then shrink
#   Batch size         = 32
#   Target update freq = 10 steps
# ============================================================

class DQNAgent:
    """
    Local DQN agent for one fog node.

    Two networks:
    1. Online network (model)       → learns continuously
    2. Target network (target_model)→ stable reference, updated slowly

    WHY TWO NETWORKS?
    If you update the target every step, it's like trying to hit a moving target.
    Keep target frozen for 10 steps → stable learning (like studying from a fixed textbook)
    """

    def __init__(self, state_size, action_size, node_id=0):
        self.state_size  = state_size
        self.action_size = action_size
        self.node_id     = node_id

        # Hyperparameters from paper
        self.gamma        = 0.95      # discount factor γ
        self.epsilon      = 1.0       # initial exploration rate
        self.epsilon_min  = 0.01      # minimum exploration
        self.epsilon_decay= 0.995     # ε decay per step
        self.batch_size   = 32        # training batch size
        self.target_freq  = 10        # how often to update target network
        self.lr           = 0.001     # learning rate α

        # Build two networks (same architecture)
        self.model        = build_dqn_model(state_size, action_size)
        self.target_model = build_dqn_model(state_size, action_size)
        self._sync_target()   # Start with identical weights

        # Replay buffer
        self.memory   = ReplayBuffer(capacity=2000)
        self.n_steps  = 0       # total steps taken
        self.loss_log = []      # track training loss

    def _sync_target(self):
        """Copy online network weights → target network."""
        self.target_model.set_weights(self.model.get_weights())

    def act(self, state):
        """
        Choose action using ε-greedy policy.

        ε-greedy means:
        - With probability ε     → random VM (EXPLORE: try something new)
        - With probability (1-ε) → best VM from Q-values (EXPLOIT: use experience)

        Early training: ε=1.0  → 100% random (manager is learning)
        Late training:  ε→0.01 → 99% smart (manager is experienced)

        Equation (26): a* = argmax_a Q(s, a)
        """
        if np.random.rand() < self.epsilon:
            # EXPLORE: random action (try a random VM)
            return random.randrange(self.action_size)

        # EXPLOIT: use neural network to pick best VM
        state_input = state.reshape(1, -1)   # shape: (1, state_size)
        q_values    = self.model.predict(state_input, verbose=0)[0]
        return int(np.argmax(q_values))       # pick VM with highest Q-value

    def remember(self, state, action, reward, next_state):
        """Store experience in replay buffer."""
        self.memory.push(state, action, reward, next_state)

    def train_step(self):
        """
        One training step using experience replay + Bellman equation.

        MATH (equation 18 from paper):
        Target = r + γ × max_a' Q(s', a'; θ⁻)   ← target network (θ⁻)
        Loss   = (Target - Q(s, a; θ))²           ← equation (19)

        Real-life:
        Manager reviews random notebook entries,
        asks "Given what I know NOW, was my past decision good?"
        Adjusts thinking accordingly.
        """
        if not self.memory.is_ready(self.batch_size):
            return None   # Not enough experiences yet

        # Sample random batch
        states, actions, rewards, next_states = self.memory.sample(self.batch_size)

        # Predict Q-values for current states (online network)
        current_q_all = self.model.predict(states, verbose=0)         # shape: (batch, actions)

        # Predict Q-values for next states (TARGET network — stable reference)
        next_q_all    = self.target_model.predict(next_states, verbose=0)

        # Build target Q-values using Bellman equation
        target_q_all  = current_q_all.copy()
        for i in range(len(states)):
            # Bellman: Q(s,a) ← r + γ × max Q(s', a')
            bellman_target = rewards[i] + self.gamma * np.max(next_q_all[i])
            target_q_all[i][actions[i]] = bellman_target

        # Train online network to match Bellman targets
        hist = self.model.fit(states, target_q_all, epochs=1, verbose=0, batch_size=self.batch_size)
        loss = hist.history['loss'][0]
        self.loss_log.append(loss)

        # Decay epsilon (become less random over time)
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

        # Periodically sync target network
        self.n_steps += 1
        if self.n_steps % self.target_freq == 0:
            self._sync_target()

        return loss

    def get_weights(self):
        """Return model weights for federated aggregation."""
        return self.model.get_weights()

    def set_weights(self, weights):
        """Accept global model weights from FL server."""
        self.model.set_weights(weights)
        self.target_model.set_weights(weights)

"""**🤝 SNIPPET 10: Federated Learning Aggregation**"""

# ============================================================
# SNIPPET 10: FEDERATED LEARNING
#
# This is what makes FLDQN different from plain DQN!
#
# SIMPLE AVERAGE (equation 20):
# θ_global = (1/N) × Σ θ_i
#
# WEIGHTED AVERAGE (equation 21) — better:
# θ_global = Σ(n_i × θ_i) / Σ(n_j)
# where n_i = number of tasks handled by node i
#
# Real-life:
# Hospital A handled 45 patients → gets 45% say in strategy
# Hospital B handled 30 patients → gets 30% say
# Hospital C handled 25 patients → gets 25% say
# Combined strategy = weighted average of all strategies
# ============================================================

def federated_aggregate_weighted(agents, tasks_per_node):
    """
    Weighted federated averaging (equation 21 from paper).

    Nodes that processed MORE tasks get MORE influence
    on the global model.

    Args:
        agents        : list of DQNAgent objects (one per fog node)
        tasks_per_node: list of int — how many tasks each node handled

    Returns:
        global_weights: averaged model weights
    """
    total_tasks = sum(tasks_per_node)

    if total_tasks == 0:
        # Fallback to simple average if no tasks processed
        return federated_aggregate_simple(agents)

    # Initialize global weights with zeros (same shape as model weights)
    global_weights = [np.zeros_like(w) for w in agents[0].get_weights()]

    for agent, n_i in zip(agents, tasks_per_node):
        weight_factor = n_i / total_tasks    # proportion: n_i / Σ n_j
        node_weights  = agent.get_weights()

        # Weighted contribution: θ_global += (n_i/Σn_j) × θ_i
        for layer_idx, layer_w in enumerate(node_weights):
            global_weights[layer_idx] += weight_factor * layer_w

    return global_weights


def federated_aggregate_simple(agents):
    """
    Simple average (equation 20): θ_global = (1/N) Σ θ_i
    Used as fallback or for comparison.
    """
    N = len(agents)
    global_weights = [np.zeros_like(w) for w in agents[0].get_weights()]

    for agent in agents:
        for i, w in enumerate(agent.get_weights()):
            global_weights[i] += w / N

    return global_weights


def broadcast_global_weights(agents, global_weights):
    """
    Send global model weights to ALL fog nodes.
    Real-life: Head office sends updated strategy manual to all branches.
    """
    for agent in agents:
        agent.set_weights(global_weights)
    # Note: actual DATA never leaves nodes — only weights are shared!

"""**🚀 SNIPPET 11: Full FLDQN Training (Main Algorithm)**"""

# ============================================================
# SNIPPET 11: MAIN FLDQN TRAINING LOOP
# This implements Algorithm 2 from the paper completely.
#
# How it works episode by episode:
# Episode 1:  All 10 node-managers start as beginners (ε=1.0, random)
# Episode 5:  Managers share what they learned → global model updated
# Episode 10: Managers get updated global strategy, continue learning
# Episode 200: Managers are highly experienced (ε≈0.01, very smart)
#
# Each episode = one full day of scheduling all tasks
# ============================================================

def run_fldqn(tasks_df,
              num_episodes        = 200,
              num_nodes           = 10,
              num_vms_per_node    = 6,
              fl_update_every     = 5,    # federated aggregation every N episodes
              verbose             = True):
    """
    Full FLDQN training (Algorithm 2 + Algorithm 3 from paper).

    Args:
        tasks_df        : DataFrame with task features (from generate_tasks_from_mi)
        num_episodes    : training episodes
        num_nodes       : fog nodes (10 in paper)
        num_vms_per_node: VMs per node (6 in paper)
        fl_update_every : federated update frequency (5 in paper)
        verbose         : print progress

    Returns:
        history dict with metrics per episode
    """
    state_size  = STATE_SIZE
    action_size = num_vms_per_node

    # Initialize environment and one agent per fog node
    env    = FogEnvironment(num_nodes=num_nodes, num_vms_per_node=num_vms_per_node)
    agents = [DQNAgent(state_size, action_size, node_id=i) for i in range(num_nodes)]

    tasks_list = tasks_df.to_dict('records')
    n_tasks    = len(tasks_list)

    # History tracking (for plotting)
    history = {k: [] for k in ['episode','makespan','throughput','energy',
                                'sla_rate','rejection_rate','avg_reward','avg_loss']}

    print(f"Starting FLDQN training: {num_episodes} episodes, {n_tasks} tasks, "
          f"{num_nodes} nodes × {num_vms_per_node} VMs")
    print("="*70)

    for ep in range(num_episodes):
        env.reset()

        total_reward = 0
        total_sla    = 0
        total_reject = 0
        total_loss   = 0
        loss_count   = 0
        tasks_per_node = [0] * num_nodes  # track workload per node

        # --- TASK SCHEDULING FOR THIS EPISODE ---

        # Shuffle tasks (simulates dynamic arrival)
        episode_tasks = tasks_list.copy()
        random.shuffle(episode_tasks)

        # HIGH PRIORITY FIRST (K-Means driven: paper ensures high priority scheduled first)
        episode_tasks.sort(key=lambda t: t['priority'], reverse=True)

        for task in episode_tasks:
            # Assign task to a fog node (round-robin based on task_id)
            node_id = int(task['task_id']) % num_nodes
            agent   = agents[node_id]

            # 1. Get state (what does this node see right now?)
            state = env.get_state(task)

            # 2. Agent decides which VM to use (ε-greedy)
            local_vm_action = agent.act(state)

            # 3. Map local VM index → global VM index
            global_vm_idx = node_id * num_vms_per_node + local_vm_action

            # 4. Execute action in environment
            next_state, reward, sla_violated, rejected = env.step(task, global_vm_idx)

            # 5. Store experience in this node's replay buffer
            agent.remember(state, local_vm_action, reward, next_state)

            # 6. Train local DQN (Algorithm 3, line 15)
            loss = agent.train_step()
            if loss is not None:
                total_loss += loss
                loss_count += 1

            # 7. Update counters
            total_reward       += reward
            tasks_per_node[node_id] += 1
            if sla_violated: total_sla    += 1
            if rejected:     total_reject += 1

        # --- FEDERATED LEARNING STEP (every fl_update_every episodes) ---
        # Paper: "global model aggregation occurs every five scheduling periods"
        if (ep + 1) % fl_update_every == 0:
            # Step 1: Aggregate weights from all nodes (equation 21)
            global_weights = federated_aggregate_weighted(agents, tasks_per_node)
            # Step 2: Send global model back to all nodes (equation 20)
            broadcast_global_weights(agents, global_weights)

        # --- COMPUTE METRICS ---
        metrics      = env.get_all_metrics()
        sla_rate     = (total_sla    / n_tasks) * 100
        reject_rate  = (total_reject / n_tasks) * 100
        avg_reward   = total_reward / n_tasks
        avg_loss     = total_loss   / loss_count if loss_count > 0 else 0

        # Store history
        history['episode'].append(ep + 1)
        history['makespan'].append(metrics['makespan'])
        history['throughput'].append(metrics['throughput'])
        history['energy'].append(metrics['energy'])
        history['sla_rate'].append(sla_rate)
        history['rejection_rate'].append(reject_rate)
        history['avg_reward'].append(avg_reward)
        history['avg_loss'].append(avg_loss)

        # Print every 20 episodes
        if verbose and (ep + 1) % 20 == 0:
            fl_indicator = " [FL SYNC]" if (ep + 1) % fl_update_every == 0 else ""
            print(f"Ep {ep+1:3d}/{num_episodes} | "
                  f"Makespan:{metrics['makespan']:7.2f} | "
                  f"Energy:{metrics['energy']:8.2f} | "
                  f"SLA:{sla_rate:5.1f}% | "
                  f"Rej:{reject_rate:5.1f}% | "
                  f"Reward:{avg_reward:5.1f}{fl_indicator}")

    print("="*70)
    print("FLDQN training complete!")
    return history

"""**📏 SNIPPET 12: Baseline Algorithms**"""

# ============================================================
# SNIPPET 12: BASELINE ALGORITHMS FOR COMPARISON
#
# Paper compares FLDQN against:
# 1. Standalone DQN (no federated learning)
# 2. GGCN (graph-based — simplified here as least-loaded greedy)
# 3. LSTM (sequential predictor)
# ============================================================

# ---- BASELINE 1: Standalone DQN (No Federated Learning) ----

def run_standalone_dqn(tasks_df, num_episodes=200, num_nodes=10, num_vms_per_node=6, verbose=True):
    """
    DQN without federated learning.
    ONE shared agent for all nodes. No weight averaging across nodes.

    Real-life: ONE manager tries to handle ALL hospitals alone.
    No knowledge sharing between branches.
    """
    state_size  = STATE_SIZE
    action_size = num_vms_per_node

    env   = FogEnvironment(num_nodes=num_nodes, num_vms_per_node=num_vms_per_node)
    agent = DQNAgent(state_size, action_size, node_id=0)  # Single agent

    history = {k: [] for k in ['episode','makespan','throughput','energy',
                                'sla_rate','rejection_rate','avg_reward']}
    tasks_list = tasks_df.to_dict('records')
    n_tasks    = len(tasks_list)

    print(f"Standalone DQN training: {num_episodes} episodes...")

    for ep in range(num_episodes):
        env.reset()
        total_reward = total_sla = total_reject = 0

        episode_tasks = sorted(tasks_list.copy(), key=lambda t: t['priority'], reverse=True)

        for task in episode_tasks:
            node_id       = int(task['task_id']) % num_nodes
            state         = env.get_state(task)
            local_vm      = agent.act(state)
            global_vm     = node_id * num_vms_per_node + local_vm
            next_s, r, sv, rj = env.step(task, global_vm)
            agent.remember(state, local_vm, r, next_s)
            agent.train_step()
            total_reward += r
            if sv: total_sla    += 1
            if rj: total_reject += 1

        m = env.get_all_metrics()
        history['episode'].append(ep + 1)
        history['makespan'].append(m['makespan'])
        history['throughput'].append(m['throughput'])
        history['energy'].append(m['energy'])
        history['sla_rate'].append((total_sla    / n_tasks) * 100)
        history['rejection_rate'].append((total_reject / n_tasks) * 100)
        history['avg_reward'].append(total_reward / n_tasks)

        if verbose and (ep + 1) % 20 == 0:
            print(f"DQN  Ep {ep+1:3d} | Makespan:{m['makespan']:7.2f} | SLA:{(total_sla/n_tasks)*100:5.1f}%")

    return history


# ---- BASELINE 2: GGCN (Least-Loaded Greedy Heuristic) ----

def run_ggcn_baseline(tasks_df, num_episodes=200, num_nodes=10, num_vms_per_node=6, verbose=True):
    """
    Graph-based heuristic (simplified GGCN).
    Strategy: Always assign task to the LEAST LOADED VM.

    Real-life: Customers always go to the shortest queue.
    No learning, no prediction — pure greedy.
    """
    env = FogEnvironment(num_nodes=num_nodes, num_vms_per_node=num_vms_per_node)
    history = {k: [] for k in ['episode','makespan','throughput','energy',
                                'sla_rate','rejection_rate','avg_reward']}
    tasks_list = tasks_df.to_dict('records')
    n_tasks    = len(tasks_list)

    print(f"GGCN baseline training: {num_episodes} episodes...")

    for ep in range(num_episodes):
        env.reset()
        total_reward = total_sla = total_reject = 0

        episode_tasks = sorted(tasks_list.copy(), key=lambda t: t['priority'], reverse=True)

        for task in episode_tasks:
            # GGCN strategy: assign to least-loaded VM
            vm_idx = int(np.argmin(env.vm_queue_lengths))
            _, r, sv, rj = env.step(task, vm_idx)
            total_reward += r
            if sv: total_sla    += 1
            if rj: total_reject += 1

        m = env.get_all_metrics()
        history['episode'].append(ep + 1)
        history['makespan'].append(m['makespan'])
        history['throughput'].append(m['throughput'])
        history['energy'].append(m['energy'])
        history['sla_rate'].append((total_sla    / n_tasks) * 100)
        history['rejection_rate'].append((total_reject / n_tasks) * 100)
        history['avg_reward'].append(total_reward / n_tasks)

        if verbose and (ep + 1) % 20 == 0:
            print(f"GGCN Ep {ep+1:3d} | Makespan:{m['makespan']:7.2f} | SLA:{(total_sla/n_tasks)*100:5.1f}%")

    return history


# ---- BASELINE 3: LSTM Sequential Scheduler ----

def run_lstm_baseline(tasks_df, num_episodes=200, num_nodes=10, num_vms_per_node=6, verbose=True):
    """
    LSTM-based scheduler.
    Uses a sequence of past states to predict next best VM.

    Real-life: Manager reads the last 10 entries in the logbook
    to predict the best next action.
    """
    state_size  = STATE_SIZE
    action_size = num_vms_per_node
    SEQ_LEN     = 3   # lookback window

    # LSTM model: sequence of states → best VM
    lstm_input = Input(shape=(SEQ_LEN, state_size))
    x = LSTM(64)(lstm_input)
    x = Dense(32, activation='relu')(x)
    output = Dense(action_size, activation='linear')(x)
    lstm_model = models.Model(inputs=lstm_input, outputs=output)
    lstm_model.compile(optimizer='adam', loss='mse')

    env = FogEnvironment(num_nodes=num_nodes, num_vms_per_node=num_vms_per_node)
    history = {k: [] for k in ['episode','makespan','throughput','energy',
                                'sla_rate','rejection_rate','avg_reward']}
    tasks_list  = tasks_df.to_dict('records')
    n_tasks     = len(tasks_list)

    # Replay buffer for LSTM
    lstm_memory = ReplayBuffer(capacity=2000)
    state_seq   = deque([np.zeros(state_size)] * SEQ_LEN, maxlen=SEQ_LEN)

    print(f"LSTM baseline training: {num_episodes} episodes...")

    for ep in range(num_episodes):
        env.reset()
        state_seq  = deque([np.zeros(state_size)] * SEQ_LEN, maxlen=SEQ_LEN)
        total_reward = total_sla = total_reject = 0

        episode_tasks = sorted(tasks_list.copy(), key=lambda t: t['priority'], reverse=True)

        for task in episode_tasks:
            node_id   = int(task['task_id']) % num_nodes
            curr_state = env.get_state(task)
            state_seq.append(curr_state)

            # Predict Q-values from sequence
            seq_input  = np.array(list(state_seq)).reshape(1, SEQ_LEN, state_size)
            q_vals     = lstm_model.predict(seq_input, verbose=0)[0]
            local_vm   = int(np.argmax(q_vals))
            global_vm  = node_id * num_vms_per_node + local_vm

            next_state, r, sv, rj = env.step(task, global_vm)
            lstm_memory.push(curr_state, local_vm, r, next_state)

            # Train LSTM occasionally
            if lstm_memory.is_ready(32) and len(lstm_memory) % 10 == 0:
                states_b, actions_b, rewards_b, next_states_b = lstm_memory.sample(32)
                seq_batch = np.stack([states_b] * SEQ_LEN, axis=1)  # Simplified sequence
                targets   = lstm_model.predict(seq_batch, verbose=0)
                for i in range(len(states_b)):
                    targets[i][actions_b[i]] = rewards_b[i]
                lstm_model.fit(seq_batch, targets, epochs=1, verbose=0)

            total_reward += r
            if sv: total_sla    += 1
            if rj: total_reject += 1

        m = env.get_all_metrics()
        history['episode'].append(ep + 1)
        history['makespan'].append(m['makespan'])
        history['throughput'].append(m['throughput'])
        history['energy'].append(m['energy'])
        history['sla_rate'].append((total_sla    / n_tasks) * 100)
        history['rejection_rate'].append((total_reject / n_tasks) * 100)
        history['avg_reward'].append(total_reward / n_tasks)

        if verbose and (ep + 1) % 20 == 0:
            print(f"LSTM Ep {ep+1:3d} | Makespan:{m['makespan']:7.2f} | SLA:{(total_sla/n_tasks)*100:5.1f}%")

    return history

"""**📊 SNIPPET 13: Visualization (Matches Paper Figures)**"""

# ============================================================
# SNIPPET 13: VISUALIZATION — MATCHES PAPER FIGURES 7-21
# ============================================================

def plot_metric_over_episodes(results_dict, metric_key, ylabel, title, filename=None):
    """
    Plot one metric across episodes for all algorithms.
    Matches paper figures style.

    Args:
        results_dict: {'FLDQN': history, 'DQN': history, ...}
        metric_key  : 'makespan', 'energy', 'sla_rate', etc.
    """
    colors  = {'FLDQN': '#2ca02c', 'DQN': '#ff7f0e', 'GGCN': '#1f77b4', 'LSTM': '#d62728'}
    widths  = {'FLDQN': 2.0,       'DQN': 1.5,       'GGCN': 1.5,       'LSTM': 1.5}

    plt.figure(figsize=(10, 5))
    for alg_name, hist in results_dict.items():
        plt.plot(
            hist['episode'],
            hist[metric_key],
            color=colors.get(alg_name, 'black'),
            linewidth=widths.get(alg_name, 1.0),
            label=alg_name,
            alpha=0.85
        )

    plt.xlabel('Episodes', fontsize=12)
    plt.ylabel(ylabel, fontsize=12)
    plt.title(title, fontsize=13, fontweight='bold')
    plt.legend(fontsize=11)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    if filename:
        plt.savefig(filename, dpi=150, bbox_inches='tight')
    plt.show()


def plot_full_comparison(results_dict, dataset_label="100 Tasks"):
    """
    Full comparison dashboard — all 5 metrics in one figure.
    """
    metrics = [
        ('makespan',       'Makespan',              'Evaluation of Makespan'),
        ('energy',         'Energy Consumption',     'Evaluation of Energy'),
        ('sla_rate',       'SLA Violation Rate (%)', 'Evaluation of SLA'),
        ('rejection_rate', 'Task Rejection (%)',     'Evaluation of Task Rejection'),
        ('throughput',     'Throughput',             'Evaluation of Throughput'),
    ]

    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    fig.suptitle(f'FLDQN vs Baselines — {dataset_label}', fontsize=15, fontweight='bold')
    axes_flat = axes.flatten()

    colors = {'FLDQN': '#2ca02c', 'DQN': '#ff7f0e', 'GGCN': '#1f77b4', 'LSTM': '#d62728'}

    for idx, (metric, ylabel, title) in enumerate(metrics):
        ax = axes_flat[idx]
        for alg, hist in results_dict.items():
            ax.plot(hist['episode'], hist[metric],
                    color=colors.get(alg, 'grey'),
                    label=alg, linewidth=1.5, alpha=0.85)
        ax.set_xlabel('Episodes')
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.3)

    fig.delaxes(axes_flat[5])   # Remove unused 6th subplot
    plt.tight_layout()
    plt.savefig(f'comparison_{dataset_label.replace(" ", "_")}.png', dpi=150, bbox_inches='tight')
    plt.show()


def print_final_results_table(results_dict, dataset_label="Dataset"):
    """
    Print final episode metrics as a clean comparison table.
    """
    print(f"\n{'='*70}")
    print(f"FINAL RESULTS SUMMARY — {dataset_label}")
    print(f"{'='*70}")
    print(f"{'Algorithm':>10} | {'Makespan':>10} | {'Energy':>10} | {'SLA %':>8} | {'Reject %':>8} | {'Throughput':>10}")
    print(f"{'-'*70}")

    for alg, hist in results_dict.items():
        mk = hist['makespan'][-1]
        en = hist['energy'][-1]
        sl = hist['sla_rate'][-1]
        rj = hist['rejection_rate'][-1]
        tp = hist['throughput'][-1]
        print(f"{alg:>10} | {mk:>10.2f} | {en:>10.2f} | {sl:>8.2f} | {rj:>8.2f} | {tp:>10.4f}")

    print(f"{'='*70}\n")

"""**🌟 SNIPPET 14: Run All Algorithms and Compare**"""

# ============================================================
# SNIPPET 14: RUN EVERYTHING FOR ALL THREE DATASET SIZES
# This is where you run all algorithms and get your results
# ============================================================

NUM_EPISODES = 5

# ---- SMALL DATASET (100 tasks) ----
print("\n" + "="*70)
print("RUNNING EXPERIMENTS: SMALL DATASET (100 tasks)")
print("="*70)

fldqn_small = run_fldqn(tasks_small, num_episodes=NUM_EPISODES, verbose=True)
dqn_small   = run_standalone_dqn(tasks_small, num_episodes=NUM_EPISODES, verbose=True)
ggcn_small  = run_ggcn_baseline(tasks_small, num_episodes=NUM_EPISODES, verbose=True)
lstm_small  = run_lstm_baseline(tasks_small, num_episodes=NUM_EPISODES, verbose=True)

results_small = {'FLDQN': fldqn_small, 'DQN': dqn_small, 'GGCN': ggcn_small, 'LSTM': lstm_small}
plot_full_comparison(results_small, "Small Dataset (100 tasks)")
print_final_results_table(results_small, "Small Dataset (100 tasks)")

# ---- MEDIUM DATASET (500 tasks) ----
print("\n" + "="*70)
print("RUNNING EXPERIMENTS: MEDIUM DATASET (500 tasks)")
print("="*70)

fldqn_medium = run_fldqn(tasks_medium, num_episodes=NUM_EPISODES, verbose=True)
dqn_medium   = run_standalone_dqn(tasks_medium, num_episodes=NUM_EPISODES, verbose=True)
ggcn_medium  = run_ggcn_baseline(tasks_medium, num_episodes=NUM_EPISODES, verbose=True)
lstm_medium  = run_lstm_baseline(tasks_medium, num_episodes=NUM_EPISODES, verbose=True)

results_medium = {'FLDQN': fldqn_medium, 'DQN': dqn_medium, 'GGCN': ggcn_medium, 'LSTM': lstm_medium}
plot_full_comparison(results_medium, "Medium Dataset (500 tasks)")
print_final_results_table(results_medium, "Medium Dataset (500 tasks)")

# ---- LARGE DATASET (1000 tasks) ----
print("\n" + "="*70)
print("RUNNING EXPERIMENTS: LARGE DATASET (1000 tasks)")
print("="*70)

fldqn_large = run_fldqn(tasks_large, num_episodes=NUM_EPISODES, verbose=True)
dqn_large   = run_standalone_dqn(tasks_large, num_episodes=NUM_EPISODES, verbose=True)
ggcn_large  = run_ggcn_baseline(tasks_large, num_episodes=NUM_EPISODES, verbose=True)
lstm_large  = run_lstm_baseline(tasks_large, num_episodes=NUM_EPISODES, verbose=True)

results_large = {'FLDQN': fldqn_large, 'DQN': dqn_large, 'GGCN': ggcn_large, 'LSTM': lstm_large}
plot_full_comparison(results_large, "Large Dataset (1000 tasks)")
print_final_results_table(results_large, "Large Dataset (1000 tasks)")

"""**🧪 SNIPPET 15: E-FLDQN Implementation**"""

# ============================================================
# SNIPPET 15: NOVEL ALGORITHM — E-FLDQN
# Enhanced Federated DQN with:
# 1. Dynamic K via Silhouette Score
# 2. Prioritized Experience Replay (PER)
# 3. SLA-Performance Weighted Federated Aggregation
# 4. Priority-Scaled Reward Function
# ============================================================

# ---- PART A: Dynamic K via Silhouette Score ----

def find_optimal_k(tasks_df, k_range=range(2, 7)):
    """
    Automatically find the best number of clusters (K)
    using Silhouette Score.

    Silhouette Score measures: "How well-separated are my clusters?"
    Score = +1 : perfect separation (clusters are distinct)
    Score =  0 : overlapping clusters
    Score = -1 : wrong cluster assignment

    Real-life: Instead of always saying "3 priority groups",
    let the DATA tell us how many natural groups exist today.

    This is E-FLDQN's first innovation over the base paper.
    """
    X = tasks_df[['exec_time', 'deadline']].values
    scaler = StandardScaler()
    X_sc   = scaler.fit_transform(X)

    best_k     = 3
    best_score = -1
    scores     = {}

    print("  Finding optimal K...")
    for k in k_range:
        if k >= len(X):   # Can't have more clusters than samples
            break
        km = KMeans(n_clusters=k, n_init=5, random_state=42)
        labels = km.fit_predict(X_sc)

        # Silhouette score only valid if k >= 2 and not all same cluster
        if len(set(labels)) > 1:
            score = silhouette_score(X_sc, labels)
            scores[k] = score
            if score > best_score:
                best_score = score
                best_k     = k

    print(f"  Silhouette scores: {scores}")
    print(f"  Optimal K = {best_k} (score = {best_score:.4f})")
    return best_k, scores


def dynamic_kmeans_prioritization(tasks_df, k_range=range(2, 7)):
    """
    K-Means with automatically determined K.

    After finding optimal K, assigns priority 0..K-1 to clusters
    sorted by urgency score (exec_time / deadline).

    This generalizes the base paper's fixed K=3 to any K.
    """
    optimal_k, sil_scores = find_optimal_k(tasks_df, k_range)

    df     = tasks_df.copy()
    X      = df[['exec_time', 'deadline']].values
    scaler = StandardScaler()
    X_sc   = scaler.fit_transform(X)

    km             = KMeans(n_clusters=optimal_k, n_init=10, random_state=42)
    df['cluster']  = km.fit_predict(X_sc)

    cluster_stats = df.groupby('cluster').agg(
        avg_exec    = ('exec_time', 'mean'),
        avg_deadline= ('deadline',  'mean')
    )
    cluster_stats['urgency'] = cluster_stats['avg_exec'] / cluster_stats['avg_deadline']

    # Rank: most urgent gets highest priority number
    urgency_rank = cluster_stats['urgency'].rank(ascending=False).astype(int)

    # Priority: 0=lowest, optimal_k-1=highest
    priority_map = {cid: int(optimal_k - rank) for cid, rank in urgency_rank.items()}
    df['priority'] = df['cluster'].map(priority_map)

    # Create human-readable labels
    max_p = df['priority'].max()
    def get_label(p):
        if p == max_p:   return 'high'
        elif p == 0:     return 'low'
        else:            return f'medium_{p}'
    df['priority_label'] = df['priority'].apply(get_label)

    return df, km, scaler, cluster_stats, optimal_k, sil_scores


# ---- PART B: Prioritized Experience Replay (PER) ----

class PrioritizedReplayBuffer:
    """
    Prioritized Experience Replay (PER).

    Standard replay: sample RANDOMLY from buffer
    PER: sample experiences where prediction ERROR was HIGH

    Why? Experiences where agent was MOST WRONG = most informative.

    Real-life: Review notebook pages where you made the BIGGEST mistakes.
    Don't waste time reviewing entries you already understand perfectly.

    Priority of experience = |TD-error| + small constant ε
    TD-error = |target_Q - predicted_Q|  ← how wrong was my prediction?

    Paper mentions PER as future direction — this implements it!
    """

    def __init__(self, capacity=2000, alpha=0.6):
        """
        Args:
            alpha: how much prioritization to use
                   0 = uniform (same as standard replay)
                   1 = full prioritization
        """
        self.capacity   = capacity
        self.alpha      = alpha
        self.buffer     = []
        self.priorities = np.zeros(capacity, dtype=np.float32)
        self.pos        = 0   # current write position
        self.size       = 0

    def push(self, state, action, reward, next_state, td_error=1.0):
        """
        Store experience with priority based on TD error.
        New experiences get max priority by default (ensure they're seen).
        """
        max_priority = self.priorities[:self.size].max() if self.size > 0 else 1.0

        if self.size < self.capacity:
            self.buffer.append((state, action, reward, next_state))
            self.size += 1
        else:
            self.buffer[self.pos] = (state, action, reward, next_state)

        self.priorities[self.pos] = max_priority  # new experience gets max priority
        self.pos = (self.pos + 1) % self.capacity

    def sample(self, batch_size=32, beta=0.4):
        """
        Sample based on priority probabilities.

        P(i) = priority_i^α / Σ priority_j^α

        Higher priority → higher chance of being selected.
        """
        if self.size < batch_size:
            batch_size = self.size

        # Compute sampling probabilities
        probs = self.priorities[:self.size] ** self.alpha
        probs = probs / probs.sum()

        # Sample indices based on priority
        indices = np.random.choice(self.size, batch_size, p=probs, replace=False)

        batch       = [self.buffer[i] for i in indices]
        states, actions, rewards, next_states = zip(*batch)

        return (
            np.array(states,      dtype=np.float32),
            np.array(actions,     dtype=np.int32),
            np.array(rewards,     dtype=np.float32),
            np.array(next_states, dtype=np.float32),
            indices
        )

    def update_priorities(self, indices, td_errors):
        """Update priorities after training (use actual TD errors)."""
        for idx, err in zip(indices, td_errors):
            self.priorities[idx] = abs(err) + 1e-5   # small constant avoids zero priority

    def is_ready(self, batch_size):
        return self.size >= batch_size


# ---- PART C: E-FLDQN Agent (Enhanced DQN Agent) ----

class EnhancedDQNAgent:
    """
    Enhanced DQN Agent with:
    1. Prioritized Experience Replay
    2. Priority-scaled reward function
    3. Slightly deeper network for better generalization
    """

    def __init__(self, state_size, action_size, node_id=0):
        self.state_size   = state_size
        self.action_size  = action_size
        self.node_id      = node_id

        # Same hyperparameters as paper + PER additions
        self.gamma        = 0.95
        self.epsilon      = 1.0
        self.epsilon_min  = 0.01
        self.epsilon_decay= 0.995
        self.batch_size   = 32
        self.target_freq  = 10
        self.per_beta     = 0.4   # PER importance sampling

        # Build model (same architecture, reuse function)
        self.model        = build_dqn_model(state_size, action_size)
        self.target_model = build_dqn_model(state_size, action_size)
        self.target_model.set_weights(self.model.get_weights())

        # PRIORITIZED replay buffer (NEW vs base paper)
        self.memory   = PrioritizedReplayBuffer(capacity=2000, alpha=0.6)
        self.n_steps  = 0
        self.loss_log = []

    def priority_scaled_reward(self, reward, task_priority):
        """
        E-FLDQN Innovation: Scale reward by task priority.

        High-priority task violation is MORE costly.
        Low-priority task violation is LESS costly.

        Standard paper reward (eq. 28):
            +10, -5, -10 for all tasks equally

        Enhanced reward:
            High priority:  +15, -10, -15  (stakes are higher)
            Medium priority: +10,  -5, -10  (same as paper)
            Low priority:    +8,   -3,  -8  (stakes are lower)

        Real-life: Missing a brain surgery deadline (high priority)
        is FAR worse than missing an elective procedure (low priority).
        """
        # Priority scaling factors
        scale = {0: 0.8, 1: 1.0, 2: 1.5}
        factor = scale.get(int(task_priority), 1.0)
        return reward * factor

    def act(self, state):
        """ε-greedy action selection (same as base paper)."""
        if np.random.rand() < self.epsilon:
            return random.randrange(self.action_size)
        q_vals = self.model.predict(state.reshape(1, -1), verbose=0)[0]
        return int(np.argmax(q_vals))

    def remember(self, state, action, reward, next_state):
        """Store in PRIORITIZED buffer."""
        self.memory.push(state, action, reward, next_state)

    def train_step(self):
        """
        Train with Prioritized Experience Replay.

        Steps:
        1. Sample by priority (not randomly)
        2. Compute TD errors for sampled batch
        3. Update model
        4. Update priorities with actual TD errors
        """
        if not self.memory.is_ready(self.batch_size):
            return None

        # Sample using priorities
        states, actions, rewards, next_states, indices = \
            self.memory.sample(self.batch_size, beta=self.per_beta)

        current_q_all = self.model.predict(states, verbose=0)
        next_q_all    = self.target_model.predict(next_states, verbose=0)

        target_q_all = current_q_all.copy()
        td_errors    = []

        for i in range(len(states)):
            bellman_target = rewards[i] + self.gamma * np.max(next_q_all[i])
            old_q          = current_q_all[i][actions[i]]
            td_error       = abs(bellman_target - old_q)   # actual prediction error
            td_errors.append(td_error)
            target_q_all[i][actions[i]] = bellman_target

        # Train model
        hist = self.model.fit(states, target_q_all, epochs=1, verbose=0,
                              batch_size=self.batch_size)
        loss = hist.history['loss'][0]
        self.loss_log.append(loss)

        # UPDATE PRIORITIES based on actual TD errors (PER key step)
        self.memory.update_priorities(indices, td_errors)

        # Decay epsilon
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

        # Sync target network
        self.n_steps += 1
        if self.n_steps % self.target_freq == 0:
            self.target_model.set_weights(self.model.get_weights())

        return loss

    def get_weights(self):
        return self.model.get_weights()

    def set_weights(self, weights):
        self.model.set_weights(weights)
        self.target_model.set_weights(weights)


# ---- PART D: SLA-Performance Weighted Federated Aggregation ----

def sla_weighted_aggregate(agents, sla_compliance_rates):
    """
    E-FLDQN Innovation: Weight aggregation by SLA compliance rate.

    Standard paper (eq. 21): weight by NUMBER of tasks handled
    E-FLDQN:                  weight by SLA SUCCESS RATE

    Formula:
        θ_global = Σ (SLA_rate_i × θ_i) / Σ SLA_rate_j

    Real-life: Hospitals with BETTER patient success rates
    have MORE influence on the shared strategy.
    A hospital with 95% success rate gets MORE say than
    one with 60% success rate — even if both handled same patients.

    Why this is better:
    Base paper assumption: more tasks = better node = more influence
    E-FLDQN insight: actual QUALITY of scheduling matters more than quantity
    """
    # Use SLA compliance as weight (higher SLA compliance = better node)
    total_weight = sum(sla_compliance_rates) + 1e-8  # avoid division by zero

    global_weights = [np.zeros_like(w) for w in agents[0].get_weights()]

    for agent, sla_rate in zip(agents, sla_compliance_rates):
        weight_factor = sla_rate / total_weight
        for i, w in enumerate(agent.get_weights()):
            global_weights[i] += weight_factor * w

    return global_weights


# ---- PART E: Full E-FLDQN Training Loop ----

def run_efldqn(tasks_df,
               num_episodes     = 200,
               num_nodes        = 10,
               num_vms_per_node = 6,
               fl_update_every  = 5,
               verbose          = True):
    """
    E-FLDQN: Enhanced FLDQN Training.

    Combines all four innovations:
    1. Dynamic K-Means (optimal K via silhouette)
    2. Prioritized Experience Replay
    3. SLA-Performance Weighted FL Aggregation
    4. Priority-Scaled Reward Function
    """
    state_size  = STATE_SIZE
    action_size = num_vms_per_node

    env    = FogEnvironment(num_nodes=num_nodes, num_vms_per_node=num_vms_per_node)
    agents = [EnhancedDQNAgent(state_size, action_size, node_id=i) for i in range(num_nodes)]

    tasks_list = tasks_df.to_dict('records')
    n_tasks    = len(tasks_list)

    history = {k: [] for k in ['episode','makespan','throughput','energy',
                                'sla_rate','rejection_rate','avg_reward','avg_loss']}

    print(f"\nStarting E-FLDQN training: {num_episodes} episodes, {n_tasks} tasks")
    print("  Innovations: Dynamic-K + PER + SLA-weighted FL + Priority-scaled Reward")
    print("="*70)

    for ep in range(num_episodes):
        env.reset()

        total_reward    = 0
        total_sla       = 0
        total_reject    = 0
        total_loss      = 0
        loss_count      = 0
        node_sla_ok     = [0] * num_nodes   # SLA successes per node
        node_total      = [0] * num_nodes   # Total tasks per node

        episode_tasks = tasks_list.copy()
        random.shuffle(episode_tasks)
        # High priority tasks scheduled FIRST (same as base paper)
        episode_tasks.sort(key=lambda t: t['priority'], reverse=True)

        for task in episode_tasks:
            node_id      = int(task['task_id']) % num_nodes
            agent        = agents[node_id]

            state        = env.get_state(task)
            local_vm     = agent.act(state)
            global_vm    = node_id * num_vms_per_node + local_vm

            next_state, raw_reward, sla_violated, rejected = env.step(task, global_vm)

            # INNOVATION 4: Scale reward by task priority
            scaled_reward = agent.priority_scaled_reward(raw_reward, task['priority'])

            agent.remember(state, local_vm, scaled_reward, next_state)
            loss = agent.train_step()
            if loss is not None:
                total_loss += loss
                loss_count += 1

            total_reward += scaled_reward
            node_total[node_id] += 1
            if sla_violated:
                total_sla += 1
            else:
                node_sla_ok[node_id] += 1   # Track per-node SLA success
            if rejected:
                total_reject += 1

        # INNOVATION 3: SLA-performance weighted federated aggregation
        if (ep + 1) % fl_update_every == 0:
            # Compute SLA compliance rate per node
            sla_compliance = [
                node_sla_ok[i] / node_total[i] if node_total[i] > 0 else 0.5
                for i in range(num_nodes)
            ]
            # Aggregate weights using SLA compliance rates
            global_weights = sla_weighted_aggregate(agents, sla_compliance)
            broadcast_global_weights(agents, global_weights)

        m            = env.get_all_metrics()
        sla_rate     = (total_sla    / n_tasks) * 100
        reject_rate  = (total_reject / n_tasks) * 100
        avg_reward   = total_reward / n_tasks
        avg_loss     = total_loss   / loss_count if loss_count > 0 else 0

        history['episode'].append(ep + 1)
        history['makespan'].append(m['makespan'])
        history['throughput'].append(m['throughput'])
        history['energy'].append(m['energy'])
        history['sla_rate'].append(sla_rate)
        history['rejection_rate'].append(reject_rate)
        history['avg_reward'].append(avg_reward)
        history['avg_loss'].append(avg_loss)

        if verbose and (ep + 1) % 20 == 0:
            print(f"E-FLDQN Ep {ep+1:3d}/{num_episodes} | "
                  f"Makespan:{m['makespan']:7.2f} | "
                  f"Energy:{m['energy']:8.2f} | "
                  f"SLA:{sla_rate:5.1f}% | "
                  f"Rej:{reject_rate:5.1f}% | "
                  f"Reward:{avg_reward:5.1f}")

    print("="*70)
    print("E-FLDQN training complete!")
    return history

"""**📊 SNIPPET 16: Apply Dynamic K-Means and Run E-FLDQN**"""

# ============================================================
# SNIPPET 16: APPLY DYNAMIC K AND RUN E-FLDQN
# ============================================================

print("Applying Dynamic K-Means to Small Dataset...")
tasks_small_efl, _, _, _, k_small, sil_small = dynamic_kmeans_prioritization(tasks_small)
print(f"  Small dataset: optimal K = {k_small}")

print("\nApplying Dynamic K-Means to Medium Dataset...")
tasks_medium_efl, _, _, _, k_medium, sil_medium = dynamic_kmeans_prioritization(tasks_medium)
print(f"  Medium dataset: optimal K = {k_medium}")

print("\nApplying Dynamic K-Means to Large Dataset...")
tasks_large_efl, _, _, _, k_large, sil_large = dynamic_kmeans_prioritization(tasks_large)
print(f"  Large dataset: optimal K = {k_large}")

# Plot silhouette scores to show how optimal K was chosen
def plot_silhouette_scores(sil_dict, dataset_name):
    plt.figure(figsize=(6, 4))
    plt.bar(list(sil_dict.keys()), list(sil_dict.values()),
            color='steelblue', edgecolor='black', alpha=0.8)
    plt.xlabel('Number of Clusters (K)', fontsize=12)
    plt.ylabel('Silhouette Score', fontsize=12)
    plt.title(f'Optimal K Selection — {dataset_name}', fontsize=13, fontweight='bold')
    plt.axhline(y=max(sil_dict.values()), color='red', linestyle='--',
                label=f'Best K={max(sil_dict, key=sil_dict.get)}')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

plot_silhouette_scores(sil_small,  "Small Dataset (100 tasks)")
plot_silhouette_scores(sil_medium, "Medium Dataset (500 tasks)")
plot_silhouette_scores(sil_large,  "Large Dataset (1000 tasks)")

# ---- RUN E-FLDQN ON ALL DATASETS ----
print("\n" + "="*70)
print("RUNNING E-FLDQN (Enhanced Algorithm)")
print("="*70)

efldqn_small  = run_efldqn(tasks_small_efl,  num_episodes=5, verbose=True)
efldqn_medium = run_efldqn(tasks_medium_efl, num_episodes=5, verbose=True)
efldqn_large  = run_efldqn(tasks_large_efl,  num_episodes=5, verbose=True)

"""**📈 SNIPPET 17: Final 5-Algorithm Comparison**"""

# ============================================================
# SNIPPET 17: FULL 5-ALGORITHM COMPARISON
# FLDQN vs DQN vs GGCN vs LSTM vs E-FLDQN (your new algorithm)
# ============================================================

def plot_5way_comparison(results_5, dataset_label):
    """
    Plot all 5 algorithms on the same charts.
    Your E-FLDQN should appear as the best line!
    """
    metrics = [
        ('makespan',       'Makespan',              'Makespan Comparison'),
        ('energy',         'Energy Consumption',     'Energy Comparison'),
        ('sla_rate',       'SLA Violation Rate (%)', 'SLA Violations'),
        ('rejection_rate', 'Task Rejection (%)',     'Task Rejection Rate'),
        ('throughput',     'Throughput',             'Throughput Comparison'),
    ]

    # Colors for all 5 algorithms
    colors = {
        'E-FLDQN': '#9b59b6',   # Purple — your new algorithm
        'FLDQN'  : '#2ca02c',   # Green
        'DQN'    : '#ff7f0e',   # Orange
        'GGCN'   : '#1f77b4',   # Blue
        'LSTM'   : '#d62728'    # Red
    }
    widths = {
        'E-FLDQN': 2.5,  # Thicker line for your algorithm
        'FLDQN'  : 2.0,
        'DQN'    : 1.5,
        'GGCN'   : 1.5,
        'LSTM'   : 1.5
    }

    fig, axes = plt.subplots(2, 3, figsize=(20, 11))
    fig.suptitle(f'5-Algorithm Comparison: E-FLDQN vs Baselines — {dataset_label}',
                 fontsize=14, fontweight='bold')
    axes_flat = axes.flatten()

    for idx, (metric, ylabel, title) in enumerate(metrics):
        ax = axes_flat[idx]
        # Plot E-FLDQN LAST so it's on top
        for alg in ['LSTM', 'GGCN', 'DQN', 'FLDQN', 'E-FLDQN']:
            if alg not in results_5:
                continue
            hist = results_5[alg]
            ax.plot(hist['episode'], hist[metric],
                    color=colors[alg],
                    linewidth=widths[alg],
                    label=alg,
                    alpha=0.85)

        ax.set_xlabel('Episodes')
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.3)

    fig.delaxes(axes_flat[5])
    plt.tight_layout()
    plt.savefig(f'5alg_{dataset_label.replace(" ","_")}.png', dpi=150, bbox_inches='tight')
    plt.show()


def print_5way_table(results_5, dataset_label):
    """Print clean comparison table for all 5 algorithms."""
    print(f"\n{'='*80}")
    print(f"5-ALGORITHM FINAL COMPARISON — {dataset_label}")
    print(f"{'='*80}")
    print(f"{'Algorithm':>12} | {'Makespan':>10} | {'Energy':>10} | {'SLA %':>8} | {'Reject %':>8} | {'Throughput':>10}")
    print(f"{'-'*80}")

    # Print in order: worst to best
    algo_order = ['LSTM', 'GGCN', 'DQN', 'FLDQN', 'E-FLDQN']
    for alg in algo_order:
        if alg not in results_5:
            continue
        h  = results_5[alg]
        mk = h['makespan'][-1]
        en = h['energy'][-1]
        sl = h['sla_rate'][-1]
        rj = h['rejection_rate'][-1]
        tp = h['throughput'][-1]
        marker = " ← BEST" if alg == 'E-FLDQN' else ""
        print(f"{alg:>12} | {mk:>10.2f} | {en:>10.2f} | {sl:>8.2f} | {rj:>8.2f} | {tp:>10.4f}{marker}")
    print(f"{'='*80}\n")


# Combine all results for 5-way comparison
results_5_small = {
    'LSTM'   : lstm_small,
    'GGCN'   : ggcn_small,
    'DQN'    : dqn_small,
    'FLDQN'  : fldqn_small,
    'E-FLDQN': efldqn_small
}

results_5_medium = {
    'LSTM'   : lstm_medium,
    'GGCN'   : ggcn_medium,
    'DQN'    : dqn_medium,
    'FLDQN'  : fldqn_medium,
    'E-FLDQN': efldqn_medium
}

results_5_large = {
    'LSTM'   : lstm_large,
    'GGCN'   : ggcn_large,
    'DQN'    : dqn_large,
    'FLDQN'  : fldqn_large,
    'E-FLDQN': efldqn_large
}

# Plot and print all
plot_5way_comparison(results_5_small,  "Small Dataset (100 tasks)")
print_5way_table(results_5_small,      "Small Dataset (100 tasks)")

plot_5way_comparison(results_5_medium, "Medium Dataset (500 tasks)")
print_5way_table(results_5_medium,     "Medium Dataset (500 tasks)")

plot_5way_comparison(results_5_large,  "Large Dataset (1000 tasks)")
print_5way_table(results_5_large,      "Large Dataset (1000 tasks)")

"""**📋 SNIPPET 18: Metrics Summary Table (like paper Tables 3-17)**"""

# ============================================================
# SNIPPET 18: GENERATE PAPER-STYLE SUMMARY TABLES
# Like Tables 3-17 in the base paper
# ============================================================

def generate_summary_table(results_dict_per_size, metric='makespan'):
    """
    Generates a summary table like Tables 3-5 in the paper.
    Rows = dataset sizes, Columns = algorithms.
    """
    size_labels = list(results_dict_per_size.keys())
    all_algs    = list(list(results_dict_per_size.values())[0].keys())

    print(f"\n{'='*60}")
    print(f"SUMMARY TABLE: {metric.upper()}")
    print(f"{'='*60}")

    header = f"{'Size':>8}" + "".join(f"{alg:>12}" for alg in all_algs)
    print(header)
    print("-"*60)

    for size_label, results_for_size in results_dict_per_size.items():
        row = f"{size_label:>8}"
        for alg in all_algs:
            val = results_for_size[alg][metric][-1]
            row += f"{val:>12.2f}"
        print(row)

    print(f"{'='*60}\n")


# Organize results by dataset size for table generation
all_sizes = {
    '100':  results_5_small,
    '500':  results_5_medium,
    '1000': results_5_large,
}

generate_summary_table(all_sizes, 'makespan')
generate_summary_table(all_sizes, 'energy')
generate_summary_table(all_sizes, 'sla_rate')
generate_summary_table(all_sizes, 'rejection_rate')
generate_summary_table(all_sizes, 'throughput')